# Generated by Django 2.2 on 2019-04-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrentcar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField()),
                ('date_end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrentcar.Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrentcar.Client')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='rents',
            field=models.ManyToManyField(through='myrentcar.Rent', to='myrentcar.Client'),
        ),
    ]
